### PR TITLE
Add basic support for nvme drives

### PR DESCRIPTION
**Pull request by jordan-thoms**
This is a pretty rough first cut at supporting NVME drives for fan control using the nvme-cli tool to get the temperature.

Not sure if this project is still maintained but if it is and you are interested in merging I can add tests and fix the support for getting the drive name etc.

### CODE REVIEW

**Comment by desbma** [comment]
Thanks for the pull request

Code wise, I'd rather have two `NvmeDrive` and `HddDrive` classes rather than trying to stuff everything in the `Drive` class. 
Clearly hard drives and NVM's are different beasts, and most of the code in the `Drive` class is tied to SATA/HDD specific logic (like the spindown stuff). Actually most of the program is, which leads me to the next point.

Why do you need NVMe support? 

This program is the equivalent of [fancontrol](https://linux.die.net/man/8/fancontrol) for hard disk drives and fills a niche use case of NAS or low power boxes which need cooling mostly/only for the hard drives. 
Given the price and novelty of NVM's I doubt NVM NAS are a thing even in high performance/professional circles. 

Also do NVM need any special cooling? Do they generate significant heat (which requires active cooling) compare to SSD which don't? Do they have a chance of getting out of their recommended operating temperature range under normal conditions? Why would they need a special treatment compared to any other PCIe device like a wifi card, which typically can get hot and often have a thermal dissipator but don't require active fans?
These are honest questions I don't know much about NVM's.

I'm not against adding support for new types of drives, but I need to be convinced first that this is worth the effort and will be useful to other people.

**Comment by jordan-thoms** [comment]
Agreed on the code organization changes, I hacked this together in half an hour or so and it shows!

The use case here is for cooling high performance NVME ssds, where heat can actually be an issue. We have an analytics server in our office with 2x Samsung 960 EVO SSDs, which can do ~2.5GB/s in sequential reads each but will reach ~80c and start to throttle their performance after ~40s of very high load - we are often putting the drives under full load for 10 minutes or more at a time, so it is a real issue in some cases.

They don't have a heatsink on them, just a thin copper layer in the label (as they have to be able to fit in laptops), we could add heatsinks to them but it could void the warranty, so the easiest way to stop them throttling is a big 3000RPM fan aimed right at them... which does the trick, but only really needs to be running when we have a lot of load and otherwise is a lot of unnecessary noise!

This may well not be useful to anyone else - as NVME drives become more common it's possible someone else may hit this issue, though most people in that situation are likely running their servers in DCs where the noise is not an issue.

**Comment by desbma** [comment]
I am surprised these things can heat up so quickly. According to the [Samsung 960 EVO manual](http://www.samsung.com/semiconductor/minisite/ssd/downloads/document/Samsung_SSD_960_EVO_Data_Sheet_Rev_1_1.pdf), they are rated for operating in the temperature range 0-70 °C.
So it means they can heat up to go well above their own operating range under high load conditions in less than one minute.
Ironically the manual even says: "_In most cases of data transfers, heavy workloads induce heat. Once temperatures reach a threshold, memory performance may be adversely affected. As the leader in SSD memory solutions, the 960 EVO adopts a new heat spreader for dissipating heat more efficiently during heavy workload use._ "

Just to be sure: are you sure you do not have a defective unit or wrong temperature reading? And do you use a case/rack which permits air flow as expected?

I don't have a NVMe myself to test, but also could you check if running `sensors`/`sensors-detect` (from lm_sensors package) can get a temperature reading from the NVM?

**Comment by jordan-thoms** [comment]
It is a little surprising if you are used to SATA SSDs, but with the new ones they are so fast that thermal throttling is a real issue. Two articles on this: https://www.pugetsystems.com/labs/articles/Samsung-950-Pro-M-2-Throttling-Analysis-776/ and the cooling which stopped it throttling: https://www.pugetsystems.com/labs/articles/Samsung-950-Pro-M-2-Throttling-Analysis-776/  Though to be clear the thermal management in these drives keeps them safe, they won't actually overheat - it's just that if you want the absolute top performance you need to keep them cool - We actually have two of these in RAID and both heat at a similar rate. Airflow is decent, not great, but given the kind of massive directed airflow it takes to keep them cool I don't think better case airflow would help much. 

Sensors/sensors-detect doesn't seem to detect them.

Anyway I fully understand if you don't want to merge this, I just figured I'd submit it back and see if there was interest. It's probably a pretty rare use case that people are running drives like this and wanting dynamic cooling on them.

**Comment by desbma** [comment]
Can you also please check if `smartctl -A` can read the NVM temperature sensor? 

I understand your use case and am willing to add NVM support, you convinced me :)

I you want to move this forward here is what I propose :
- I will refractor the current master code a bit in a `nvm-support` branch. They are several little things to do to cleanly separate what is device specific and what is not. For example because the NVM can heat up very quickly (in seconds according to the article you linked), the probe interval must be a lot shorter than for hard drives
- Then you can add and test your changes against that branch. I will have to trust you on this because I have no NVM device myself. If you have ideas to improve automated test coverage, I'm also open because the current tests are not that great.

**Comment by nightah** [comment]
@desbma looking at the history on this and the fact that there's been no response from @jordan-thoms is there any chance you plan to follow up on your last suggested action?

I'm happy to test your refactored code in another branch for NVM devices.

I have a couple NVM drives that sit alongside my other mechanical drives that often get slightly hotter than the thresholds I set to generate S.M.A.R.T alerts for me. Ideally if hddfancontrol can monitor these alongside my mechanical drives, that would be great.

Keen to assist and progress this if possible.

**Comment by jordan-thoms** [comment]
Ah, I had forgot about this! I'm still running hacked-up version made for this a few years ago. Would be happy to test a new version.

**Comment by desbma** [comment]
If there is enough interest, and since NVM are getting more common, I'll hack something together when I have some time.

The `cpu-temp` branch already has support for a different type of device, so that should be a bit easier code wise.

**Comment by desbma** [comment]
@jordan-thoms  
Does `sudo smartctl -A /dev/sda | grep Temperature_Celsius` report the temperature for your NVMe devices? You need [smartmontools >= 6.5](https://www.smartmontools.org/wiki/NVMe_Support#SmartmontoolsNVMesupport1).

I am looking at `smartctl` for #21, and it might also transparently add support for NVM if that works.

**Comment by desbma** [comment]
I'm closing this for inactivity.

I have merged smartcl code in the master branch, so I think full NVM support is not far, if not already working.

**Pull request closed without merging**
